### ISSUE TITLE
Generated migration has "DOUBLE PRECISION" instead of "DOUBLE"

### ISSUE THREAD

**Issue by Axure** [flexxnn/sequelize-auto-migrations#11]
For example, for two double fields, I got:

                "contribution": {
                    "type": Sequelize.DOUBLE PRECISION
                },
                "reputation": {
                    "type": Sequelize.DOUBLE PRECISION
                },

instead of:

                "contribution": {
                    "type": Sequelize.DOUBLE 
                },
                "reputation": {
                    "type": Sequelize.DOUBLE 
                },

**Comment by Axure** [comment]
It seems the problem has been fixed by the latest pull request. But the npm package is not updated.

**Comment by flexxnn** [comment]
Fixed in 1.0.3

**Comment by BugKiller-tech** [comment]
I still have this problem in 1.0.3
