### ISSUE TITLE
BIGINT is not defined

### ISSUE THREAD

**Issue by didac-wh** [flexxnn/sequelize-auto-migrations#14]
I tried to add a new column which is a BIGINT. The generated migration file didnt include the "Sequelize."BIGINT in the type, only "BIGINT".

Adding "Sequelize." fixed it, so it probably is a easy-to-solve issue.

tl;dr: Covert BIGINT to Sequelize.BIGINT in migration file.

I'm using Postgresql

Keep the nice work :) Thanks

**Comment by flexxnn** [comment]
Fixed in 1.0.3
