### ISSUE TITLE
Can I use this module with sequelize-typescript?

### ISSUE THREAD

**Issue by brud** [flexxnn/sequelize-auto-migrations#2]
I prefer to use https://github.com/RobinBuschmann/sequelize-typescript for defining my models. Do your module work with it?

**Comment by hiradimir** [comment]
I am using sequelize-auto-migrations with sequelize-typescript.

sequelize-cli snipet created by `sequelize init` is not support sequelize-typescript model.
you need to change model loading manually.

sample is below.

```js
// models/index.js
'use strict';

var fs = require('fs');
var path = require('path');
var parseDbUrl = require("parse-database-url");
var Sequelize = require('sequelize-typescript').Sequelize;
var basename = path.basename(__filename);
var env = process.env.NODE_ENV || 'development';
var config = require(__dirname + '/../config/config.json')[env];
var db = {};

var dbConfig = parseDbUrl(process.env[config.use_env_variable]);

var sequelize = new Sequelize({
  name: dbConfig.database,
  username: dbConfig.user,
  password: dbConfig.password,
  dialect: dbConfig.driver,
  host: dbConfig.host,
  port: dbConfig.port,
  modelPaths: [__dirname + '/../dist/js/main/models'] // you must prepare compiled javascript source.
});

Object.keys(sequelize.models).forEach((modelName) => {
  db[modelName] = sequelize.models[modelName];
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

**Comment by Axure** [comment]
I think it does. There's no need to write in the flavor of the `index.js` generated by sequelize-cli. You just need the two objects: `Sequelize`, which is the node module, and `sequelize`, which is the sequelize instance.

And to prevent sequelize-typescript to mis-treat the `index.ts` or `index.js` file as a model, you may change the `modelPaths` to another location.

Generally, you can write in the following spirit:

```typescript
'use strict';

import {Sequelize} from 'sequelize-typescript';

const db: any = {};
const devConfig = require('../config/config.json').development;

const sequelize = new Sequelize(Object.assign({
  username: 'devuser',
  password: 'somepassword',
  name: 'devdb',
  host: '127.0.0.1',
  dialect: 'postgres',
  validateOnly: false,
  modelPaths: [__dirname + '/../models/inuse']
}, devConfig));

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

**Comment by velddev** [comment]
This didn't seem to work for me anymore. instead, I created a fork for our project which directly integrates with sequelize-typescript. In case anyone gets issues with this I'll leave a link https://github.com/top-gg/sequelize-typescript-auto-migrations
