### ISSUE TITLE
NPM package Not updated

### ISSUE THREAD

**Issue by jazzyinstyle** [flexxnn/sequelize-auto-migrations#28]
The package in NPM registry needs to be updated to reflect the current state in Github.

I have downloaded from NPM version 1.0.2 but the makemigration.js & runmigration.js are missing the Option parameters:

 { name: 'migrations-path', type: String, description: 'The path to the migrations folder' },
 { name: 'models-path', type: String, description: 'The path to the models folder' },

Appreciate your help. 
Thanks.

**Comment by flexxnn** [comment]
NPM registry was updated, version 1.0.3
