### ISSUE TITLE
Store revision number in db instead if _current.json

### ISSUE THREAD

**Issue by ivictbor** [flexxnn/sequelize-auto-migrations#44]
Hello there. 
Thanks for the great project first of all. Generation of migrations is really missed feature in sequalize.
Just wondering was you thinking about storing state of migration in database directly like in Django/south/alembic and so on? This will allow applying migrations automatically, and each machine will not require to store file.
Most migration systems do it in this way, so just interesting was you thinking about some profits when decided to store state in filesystem or it was just to save time. 
I am a manager of a small development company and we are using this package a lot. I am going to implement storing in db in some feature. What would you recommend, to make a fork or create pull-request?

**Comment by Scimonster** [comment]
I'm not the maintainer, but check out the log-migrations branch here which seems to be this feature in progress.

What I personally do is use this tool to generate the migrations, and the official Sequelize CLI to run them, which stores in the DB.

**Comment by ivictbor** [comment]
found implemented this correctly by @manuelvillar in this fork https://github.com/manuelvillar/sequelize-auto-migrations-ng , and I've made some compatibility fixes there to make it work nowerdays. 
Closing issue
