### ISSUE TITLE
'No changes found' for first migration

### ISSUE THREAD

**Issue by assapir** [flexxnn/sequelize-auto-migrations#54]
Trying to create the first migration 
```
node_modules/.bin/makemigration --name init
```
resulting 
```
No changes found
```
although there are 3 new models in the models `models-path`

**Comment by tjshamhu** [comment]
Was this ever resolved?

**Comment by assapir** [comment]
Not that I am aware of

**Comment by douglas-treadwell** [comment]
@assapir @tjsamhu

I'm guessing you didn't import your models?

```js
Object.keys(models).forEach((modelName) => {
    db[modelName] = sequelize.import(models[modelName]);
});
```

**Comment by Asinging** [comment]
> 

this help solve my issues thanks you
