### ISSUE TITLE
.sequelizerc configuration isn't supported

### ISSUE THREAD

**Issue by juanjalvarez** [flexxnn/sequelize-auto-migrations#6]
Custom paths defined in `.sequelrc` aren't supported since the lib uses hardcoded paths.

**Comment by ALiangLiang** [comment]
same problem here

**Comment by sapeish** [comment]
+1

**Comment by bongster** [comment]
@ALiangLiang i also found that code. so how can set migrations-path in command line?

**Comment by bongster** [comment]
My case i wanna run `makemigration` command in upper folder like that

```
src
  - migrations
  - models
package.json
```
So i re declare the `PWD` env in package.json file like that 

`PWD=$PWD/src node ./node_modules/sequelize-auto-migrations/bin/makemigration`

**Comment by osvaldokalvaitir** [comment]
Has this problem been fixed? I am not able to generate the migrations and I believe it is because of my .sequelizerc
